import { useEffect, useState } from 'react';
import './sustainability-mock.css';

const SOURCES = [
  { recipe: 'Roast Duck',        ingredient: 'Duck carcasses', kg: 1.2, emoji: '🦆' },
  { recipe: 'Citrus Salad',      ingredient: 'Lemon peels',    kg: 0.8, emoji: '🍋' },
  { recipe: 'Sourdough service', ingredient: 'Bread crusts',   kg: 2.4, emoji: '🍞' },
];

const RESULT = {
  name: 'Citrus-glazed Duck Consommé',
  sub: 'with toasted herb croutons',
  pulled: ['Duck carcasses', 'Lemon peels', 'Bread crusts'],
  savedKg: 4.4,
  reductionPct: 87,
  costEur: 38,
};

const TOTAL = 12;

export default function SustainabilityMock() {
  const [step, setStep] = useState(0);

  useEffect(() => {
    const id = window.setInterval(() => setStep((s) => (s + 1) % TOTAL), 800);
    return () => window.clearInterval(id);
  }, []);

  const sourceVisible = (i: number) => step > i;
  const wastePulse = step >= 4 && step <= 9;
  const scanning = step === 5;
  const resultVisible = step >= 6;

  return (
    <div className="sustain-wrap">
      <div className="sustain-card">
        <div className="sustain-head">
          <div>
            <div className="sustain-head-title">Waste analysis · this week</div>
            <div className="sustain-head-sub">Scanning recipes for recoverable ingredients</div>
          </div>
          <div className="sustain-head-status">
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#6BD16B" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 3" />
            </svg>
            <span>ANALYSING</span>
          </div>
        </div>

        <div className="sustain-sources">
          <div className="sustain-sources-label">Recipes producing waste</div>
          <div className="sustain-sources-list">
            {SOURCES.map((s, i) => (
              <div
                key={s.ingredient}
                className="sustain-source"
                style={{
                  opacity: sourceVisible(i) ? 1 : 0,
                  transform: sourceVisible(i) ? 'translateY(0)' : 'translateY(6px)',
                }}
              >
                <div className="sustain-emoji">{s.emoji}</div>
                <div className="sustain-info">
                  <div className="sustain-recipe">{s.recipe}</div>
                  <div className="sustain-waste-row">
                    <span className={`sustain-waste-pill ${wastePulse ? 'pulse' : ''}`}>
                      waste · {s.ingredient}
                    </span>
                  </div>
                </div>
                <div className="sustain-kg">
                  {s.kg.toFixed(1)}<span> kg/wk</span>
                </div>
              </div>
            ))}
            {scanning && <div className="sustain-scan" />}
          </div>
          <div className={`sustain-arrow ${resultVisible ? 'on' : ''}`}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <path d="M6 9l6 6 6-6" />
            </svg>
          </div>
        </div>

        <div className={`sustain-result ${resultVisible ? 'on' : ''}`}>
          <div className="sustain-result-meta">
            <span className="sustain-new">New recipe</span>
            <span className="sustain-by">generated by <strong>ROA</strong></span>
          </div>
          <div className="sustain-result-name">{RESULT.name}</div>
          <div className="sustain-result-sub">{RESULT.sub}</div>
          <div className="sustain-result-tags">
            {RESULT.pulled.map((p) => <span key={p} className="sustain-tag">↻ {p}</span>)}
          </div>
          <div className="sustain-stats">
            {[
              { v: RESULT.savedKg.toFixed(1), u: 'kg',  l: 'Saved / wk' },
              { v: String(RESULT.reductionPct), u: '%',   l: 'Waste cut' },
              { v: `€${RESULT.costEur}`,        u: '/wk', l: 'Margin gained' },
            ].map((m) => (
              <div key={m.l}>
                <div className="sustain-stat-val">{m.v}<span>{m.u}</span></div>
                <div className="sustain-stat-lbl">{m.l}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
